"""build_treasury_auctions.py — US Treasury Auction Results

Auto-generated by Protocol Automaton spoke_smith.py at 2026-04-26T10:40:23.930273+00:00.
Spec: automaton/pending_spokes.yaml#treasury_auctions

Primary dealer takedown %, foreign bid %, bid-to-cover. Free from
TreasuryDirect. FRED has rates but NOT auction internals. Tells you
when bond-market stress is forming days before headlines.

Output: treasury_auctions.csv (workspace root)
Cache: .treasury_auctions_cache.json (TTL 24h)
"""

import csv
import io
import json
import time
import urllib.request
import urllib.error
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).parent
CACHE_FILE = ROOT / ".treasury_auctions_cache.json"
OUTPUT_FILE = ROOT / "treasury_auctions.csv"
CACHE_TTL_HOURS = 24
SOURCE_URL = "https://www.treasurydirect.gov/TA_WS/securities/announced?format=json"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Catalyst Edge Spoke / treasury_auctions)",
    "Accept": "*/*",
}


def load_cache():
    if not CACHE_FILE.exists():
        return None
    try:
        d = json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return None
    age_hours = (time.time() - d.get("ts", 0)) / 3600.0
    if age_hours > CACHE_TTL_HOURS:
        return None
    return d.get("payload")


def save_cache(payload):
    CACHE_FILE.write_text(json.dumps({"ts": time.time(), "payload": payload}),
                          encoding="utf-8")


def fetch():
    cached = load_cache()
    if cached is not None:
        print(f"  using cache (age < {CACHE_TTL_HOURS}h)")
        return cached
    try:
        req = urllib.request.Request(SOURCE_URL, headers=HEADERS)
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = resp.read().decode("utf-8", errors="replace")
        save_cache(body)
        return body
    except urllib.error.URLError as e:
        print(f"  FETCH FAILED: {e}")
        return None
    except Exception as e:  # noqa: BLE001
        print(f"  FETCH ERROR: {type(e).__name__}: {e}")
        return None


def parse(body):
    """TODO: implement parsing per spec output_schema.
    Expected output: list[dict] with keys ticker, ts, plus spoke-specific fields.
    Spec required fields: ['cusip', 'issue_date', 'security_type', 'bid_to_cover_ratio', 'primary_dealer_accepted', 'direct_bidder_accepted', 'indirect_bidder_accepted', 'high_yield']
    Spec output schema: {'auction_stress_score': 'float', 'foreign_demand_pct': 'float', 'dealer_takedown_pct': 'float'}
    """
    rows = []
    try:
        text = body if isinstance(body, str) else body.decode("utf-8", errors="replace")
        reader = csv.DictReader(io.StringIO(text), delimiter=",")
        wanted = ["cusip", "issue_date", "security_type", "bid_to_cover_ratio", "primary_dealer_accepted", "direct_bidder_accepted", "indirect_bidder_accepted", "high_yield"]
        for rec in reader:
            row = {}
            for k in wanted:
                if k in rec:
                    row[k] = rec[k]
            row.setdefault("ticker", rec.get("ticker") or rec.get("symbol") or rec.get("Symbol") or "")
            row["ts"] = (rec.get("ts") or rec.get("date") or rec.get("Date") or "")
            rows.append(row)
            if len(rows) >= 5000:
                break
    except Exception as e:
        print(f"  delimited parse error: {e}")
    return rows


def write(rows):
    if not rows:
        # Write empty file with header so audit can detect "ran but no data"
        OUTPUT_FILE.write_text("ticker,ts,status\n", encoding="utf-8")
        print(f"  wrote 0 rows to {OUTPUT_FILE.name} (empty)")
        return
    keys = list(rows[0].keys())
    with OUTPUT_FILE.open("w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=keys)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"  wrote {len(rows)} rows to {OUTPUT_FILE.name}")


def main():
    print(f"[{datetime.now(timezone.utc).isoformat()}] treasury_auctions fetching...")
    body = fetch()
    if body is None:
        print(f"  no body — exit 1")
        return 1
    rows = parse(body)
    write(rows)
    print(f"  status=ok rows={len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
