"""build_gdelt_events.py — GDELT Geopolitical Events

Auto-generated by Protocol Automaton spoke_smith.py at 2026-04-26T18:00:09.525966+00:00.
Spec: automaton/pending_spokes.yaml#gdelt_events

Tracks ~every event mentioned in news worldwide, structured. Free.
Especially valuable for international tickers + macro plays.
Complements News Momentum (event-coded vs headline-aggregated).

Output: gdelt_events.csv (workspace root)
Cache: .gdelt_events_cache.json (TTL 1h)
"""

import csv
import io
import json
import time
import urllib.request
import urllib.error
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).parent
CACHE_FILE = ROOT / ".gdelt_events_cache.json"
OUTPUT_FILE = ROOT / "gdelt_events.csv"
CACHE_TTL_HOURS = 1
SOURCE_URL = "http://data.gdeltproject.org/gdeltv2/lastupdate.txt"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Catalyst Edge Spoke / gdelt_events)",
    "Accept": "*/*",
}


def load_cache():
    if not CACHE_FILE.exists():
        return None
    try:
        d = json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return None
    age_hours = (time.time() - d.get("ts", 0)) / 3600.0
    if age_hours > CACHE_TTL_HOURS:
        return None
    return d.get("payload")


def save_cache(payload):
    CACHE_FILE.write_text(json.dumps({"ts": time.time(), "payload": payload}),
                          encoding="utf-8")


def fetch():
    cached = load_cache()
    if cached is not None:
        print(f"  using cache (age < {CACHE_TTL_HOURS}h)")
        return cached
    try:
        req = urllib.request.Request(SOURCE_URL, headers=HEADERS)
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = resp.read().decode("utf-8", errors="replace")
        save_cache(body)
        return body
    except urllib.error.URLError as e:
        print(f"  FETCH FAILED: {e}")
        return None
    except Exception as e:  # noqa: BLE001
        print(f"  FETCH ERROR: {type(e).__name__}: {e}")
        return None


def parse(body):
    """TODO: implement parsing per spec output_schema.
    Expected output: list[dict] with keys ticker, ts, plus spoke-specific fields.
    Spec required fields: ['event_id', 'event_date', 'actor1_country', 'actor2_country', 'event_code', 'goldstein_scale', 'num_mentions', 'avg_tone']
    Spec output schema: {'country_event_density': 'dict', 'country_tone_30d': 'dict'}
    """
    rows = []
    # TODO: parser_writer could not auto-detect format for 'gdelt_events'.
    # Spec source: http://data.gdeltproject.org/gdeltv2/lastupdate.txt
    # Spec required fields: ['event_id', 'event_date', 'actor1_country', 'actor2_country', 'event_code', 'goldstein_scale', 'num_mentions', 'avg_tone']
    # Spec output schema: {'country_event_density': 'dict', 'country_tone_30d': 'dict'}
    #
    # Action: LLM fallback (llm_parser_writer.py) will be invoked next.
    # If both heuristic and LLM fail, manually write a parser that returns
    # list[dict] with the schema above, then run:
    #   python3 /home/operator/.openclaw/workspace/automaton/spoke_audit.py --name gdelt_events
    return rows


def write(rows):
    if not rows:
        # Write empty file with header so audit can detect "ran but no data"
        OUTPUT_FILE.write_text("ticker,ts,status\n", encoding="utf-8")
        print(f"  wrote 0 rows to {OUTPUT_FILE.name} (empty)")
        return
    keys = list(rows[0].keys())
    with OUTPUT_FILE.open("w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=keys)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"  wrote {len(rows)} rows to {OUTPUT_FILE.name}")


def main():
    print(f"[{datetime.now(timezone.utc).isoformat()}] gdelt_events fetching...")
    body = fetch()
    if body is None:
        print(f"  no body — exit 1")
        return 1
    rows = parse(body)
    write(rows)
    print(f"  status=ok rows={len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
