#!/usr/bin/env python3
"""spoke_gamma.py — Options Gamma Well injector (Phase 4.6 wire-up).

Reads options_flow.csv (generated by fetch_options_flow.py / build_options_flow.py),
normalises gamma_score (0–10 integer) → gammaSize (0.0–1.0 float), and writes
the value directly into entity_master.json so the Three.js Gamma Well renderer
can pick it up immediately.

gammaSize > 0.2 → well rendered (threshold set in CerebroHUD.jsx)
gammaSize > 0.5 → medium well (~35-unit radius sphere)
gammaSize = 1.0 → maximum well (~55-unit radius sphere, brightest churn)

Run:
  python3 spoke_gamma.py              — full sweep from today's options_flow.csv
  python3 spoke_gamma.py --dry-run    — print would-be updates, no writes
  python3 spoke_gamma.py --min=4      — only wire tickers scoring >= N (default 0)

Schedule: append a call to this after fetch_options_flow.py in run_daily_sec_catalyst.sh
"""
from __future__ import annotations

import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT            = Path(__file__).parent
ENTITY_MASTER   = ROOT / "entity_master.json"
OPTIONS_CSV     = ROOT / "options_flow.csv"
GAMMA_SCORE_MAX = 10.0   # fetch_options_flow.py caps at 10


def _normalise(raw: float) -> float:
    """Map 0–10 gamma_score to 0.0–1.0 gammaSize, clipped."""
    return round(min(max(raw / GAMMA_SCORE_MAX, 0.0), 1.0), 4)


def wire_gamma(dry_run: bool = False, min_score: int = 0) -> None:
    print(f"[spoke_gamma] {datetime.now(timezone.utc).isoformat()}")
    print(f"  Mode: {'DRY RUN' if dry_run else 'LIVE'} | min_score: {min_score}")

    if not ENTITY_MASTER.exists():
        print("ERROR: entity_master.json not found.", file=sys.stderr)
        sys.exit(1)

    if not OPTIONS_CSV.exists():
        print("ERROR: options_flow.csv not found. Run fetch_options_flow.py first.", file=sys.stderr)
        sys.exit(1)

    em: dict = json.loads(ENTITY_MASTER.read_text(encoding="utf-8"))

    # ── Step 1: Reset all gammaSize to 0 (expired whale bets clear daily) ──────
    cleared = 0
    for rec in em.values():
        if rec.get("gammaSize", 0) != 0:
            rec["gammaSize"] = 0.0
            cleared += 1

    # ── Step 2: Read options_flow.csv and inject normalized gammaSize ──────────
    wired   = 0
    skipped = 0

    with OPTIONS_CSV.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            ticker = (row.get("ticker") or "").strip().upper()
            if not ticker:
                continue

            try:
                raw = float(row.get("gamma_score") or 0)
            except ValueError:
                continue

            if raw < min_score:
                skipped += 1
                continue

            gamma_size = _normalise(raw)

            if ticker not in em:
                skipped += 1
                continue

            if dry_run:
                if gamma_size > 0.2:
                    print(f"  [DRY] {ticker}  gamma_score={raw:.0f}  →  gammaSize={gamma_size}")
                wired += 1
                continue

            em[ticker]["gammaSize"] = gamma_size

            if gamma_size > 0.2:
                tier = "MEGA" if gamma_size >= 0.8 else "HIGH" if gamma_size >= 0.5 else "ACTIVE"
                print(f"  [{tier}] {ticker}  gamma_score={raw:.0f}  →  gammaSize={gamma_size}")
            wired += 1

    # ── Step 3: Write back ────────────────────────────────────────────────────
    if not dry_run:
        ENTITY_MASTER.write_text(json.dumps(em, indent=2), encoding="utf-8")

    print(f"\n  ✅ Gamma wiring complete")
    print(f"     Cleared (expired)  : {cleared}")
    print(f"     Wired (active)     : {wired}")
    print(f"     Skipped (no match) : {skipped}")
    wells = sum(1 for r in em.values() if (r.get("gammaSize") or 0) > 0.2)
    if not dry_run:
        print(f"     Active gamma wells : {wells}")


if __name__ == "__main__":
    dry  = "--dry-run" in sys.argv
    minv = int(next((a.split("=")[1] for a in sys.argv if a.startswith("--min=")), 0))
    wire_gamma(dry_run=dry, min_score=minv)
