from pathlib import Path


path = Path("/home/operator/.openclaw/workspace/hud/src/NodeInspector.jsx")
text = path.read_text(encoding="utf-8")

old = """  const [detail,    setDetail]    = useState(null)\n  const [loading,   setLoading]   = useState(false)\n  const [aiData,    setAiData]    = useState(null)   // { summary, confidence, catalyst_type, filing_type, filing_date }\n  const [aiLoading, setAiLoading] = useState(false)\n"""
new = """  const [detail,    setDetail]    = useState(null)\n  const [loading,   setLoading]   = useState(false)\n  const [aiData,    setAiData]    = useState(null)   // { summary, confidence, catalyst_type, filing_type, filing_date, model_metadata }\n  const [aiLoading, setAiLoading] = useState(false)\n"""
if old not in text:
    raise SystemExit("state block not found")
text = text.replace(old, new, 1)

old = """  const velocityEvent = detail?.velocity_event || node.velocityEvent || null\n  const sparks   = detail?.sparks || node.sparks || {}\n  const totalVel = Number(velocityEvent?.total_velocity ?? (\n    (sparks.patent || 0) + (sparks.legal || 0) +\n    (sparks.digital || 0) + (sparks.options || 0) + (sparks.weather || 0)\n  ))\n  const sectorColor = SECTOR_COLORS[node.sector] || '#374151'\n  const gics = detail?.gics || {}\n  const sourceTone = aiData?.source === 'verified_fallback'\n    ? { label: 'verified filing context', accent: 'var(--hud-cyan)', bg: 'rgba(114,229,255,0.08)', border: 'rgba(114,229,255,0.18)' }\n    : aiData?.source === 'unverified_fallback'\n      ? { label: 'review required', accent: 'var(--hud-warning)', bg: 'rgba(255,191,105,0.08)', border: 'rgba(255,191,105,0.22)' }\n      : aiData?.pending\n        ? { label: 'endpoint pending', accent: 'var(--hud-muted)', bg: 'rgba(255,255,255,0.04)', border: 'rgba(255,255,255,0.08)' }\n        : { label: 'model synthesis', accent: 'var(--hud-gold)', bg: 'rgba(215,180,106,0.08)', border: 'rgba(215,180,106,0.18)' }\n  const sympathyHistory = aiData?.sympathy_history || detail?.sympathy_history || []\n  const memoryContext = aiData?.memory_context || detail?.memory_context || []\n"""
new = """  const velocityEvent = detail?.velocity_event || node.velocityEvent || null\n  const sparks   = detail?.sparks || node.sparks || {}\n  const totalVel = Number(velocityEvent?.total_velocity ?? (\n    (sparks.patent || 0) + (sparks.legal || 0) +\n    (sparks.digital || 0) + (sparks.options || 0) + (sparks.weather || 0)\n  ))\n  const sectorColor = SECTOR_COLORS[node.sector] || '#374151'\n  const gics = detail?.gics || {}\n  const modelMetadata = aiData?.model_metadata || null\n  const sourceTone = aiData?.source === 'verified_fallback'\n    ? { label: 'verified filing context', accent: 'var(--hud-cyan)', bg: 'rgba(114,229,255,0.08)', border: 'rgba(114,229,255,0.18)' }\n    : aiData?.source === 'unverified_fallback'\n      ? { label: 'review required', accent: 'var(--hud-warning)', bg: 'rgba(255,191,105,0.08)', border: 'rgba(255,191,105,0.22)' }\n      : aiData?.pending\n        ? { label: 'endpoint pending', accent: 'var(--hud-muted)', bg: 'rgba(255,255,255,0.04)', border: 'rgba(255,255,255,0.08)' }\n        : { label: 'model synthesis', accent: 'var(--hud-gold)', bg: 'rgba(215,180,106,0.08)', border: 'rgba(215,180,106,0.18)' }\n  const modelTone = aiData?.pending\n    ? { color: 'rgba(158,168,186,0.82)', bg: 'rgba(255,255,255,0.03)', border: 'rgba(255,255,255,0.06)' }\n    : modelMetadata?.is_fallback\n      ? { color: 'var(--hud-warning)', bg: 'rgba(255,191,105,0.08)', border: 'rgba(255,191,105,0.18)' }\n      : { color: 'var(--hud-cyan)', bg: 'rgba(114,229,255,0.08)', border: 'rgba(114,229,255,0.16)' }\n  const modelLabel = aiData?.pending\n    ? 'endpoint offline'\n    : modelMetadata?.display_name || (modelMetadata?.is_fallback ? 'fallback path' : 'model offline')\n  const sympathyHistory = aiData?.sympathy_history || detail?.sympathy_history || []\n  const memoryContext = aiData?.memory_context || detail?.memory_context || []\n"""
if old not in text:
    raise SystemExit("model/source block not found")
text = text.replace(old, new, 1)

old = """          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>\n            <span style={{ fontSize: 8, color: 'rgba(158,168,186,0.82)', letterSpacing: 1, fontFamily: HUD_FONTS.mono }}>claude haiku</span>\n            <span style={{ padding: '5px 10px', borderRadius: 999, background: sourceTone.bg, border: `1px solid ${sourceTone.border}`, color: sourceTone.accent, fontFamily: HUD_FONTS.mono, fontSize: 8, fontWeight: 700, letterSpacing: '0.16em', textTransform: 'uppercase' }}>\n              {sourceTone.label}\n            </span>\n          </div>\n"""
new = """          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>\n            <span style={{\n              padding: '5px 10px',\n              borderRadius: 999,\n              background: modelTone.bg,\n              border: `1px solid ${modelTone.border}`,\n              color: modelTone.color,\n              fontSize: 8,\n              letterSpacing: 1,\n              fontFamily: HUD_FONTS.mono,\n              textTransform: 'uppercase',\n            }}>\n              {modelLabel}\n            </span>\n            <span style={{ padding: '5px 10px', borderRadius: 999, background: sourceTone.bg, border: `1px solid ${sourceTone.border}`, color: sourceTone.accent, fontFamily: HUD_FONTS.mono, fontSize: 8, fontWeight: 700, letterSpacing: '0.16em', textTransform: 'uppercase' }}>\n              {sourceTone.label}\n            </span>\n          </div>\n"""
if old not in text:
    raise SystemExit("badge block not found")
text = text.replace(old, new, 1)

path.write_text(text, encoding="utf-8")
