"""spoke_smith.py — Generate build_<name>.py from a Protocol Automaton spec.

Input  : /home/operator/.openclaw/workspace/automaton/pending_spokes.yaml
Output : /home/operator/.openclaw/workspace/build_<name>.py
         + spec entry transitioned queued → in_progress

The generated build script follows the existing build_*.py pattern in this
workspace: stdlib-only, urllib for HTTP, csv for output, file cache for TTL.
The wsl_sidecar_run_all.sh glob `build_*.py` picks it up automatically.

Run modes:
    python3 spoke_smith.py --next        # pop highest-priority queued spoke
    python3 spoke_smith.py --name X      # generate one specific spoke by name
    python3 spoke_smith.py --dry-run     # show what would be generated, no write

Exit codes:
    0  generated and verified (one trial run succeeded)
    1  no eligible spokes in queue
    2  validation failed — spec missing required fields
    3  network/blocker_check failed
"""

import argparse
import datetime as dt
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.request
import urllib.error
from pathlib import Path

ROOT = Path("/home/operator/.openclaw/workspace")
QUEUE_PATH = ROOT / "automaton" / "pending_spokes.yaml"
LOG_PATH = ROOT / "logs" / "spoke_smith.log"
TEMPLATE_DIR = ROOT / "automaton" / "templates"
TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)


def log(msg: str) -> None:
    ts = dt.datetime.now(dt.timezone.utc).isoformat()
    line = f"[{ts}] {msg}\n"
    with LOG_PATH.open("a", encoding="utf-8") as fh:
        fh.write(line)
    sys.stdout.write(line)


def load_yaml(path: Path) -> dict:
    """Minimal YAML loader sufficient for our spec shape (no anchors, no flow)."""
    try:
        import yaml  # type: ignore
        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except ImportError:
        log("WARN: PyYAML not installed — using fallback parser (limited)")
        return _fallback_yaml(path.read_text(encoding="utf-8"))


def dump_yaml(data: dict, path: Path) -> None:
    try:
        import yaml  # type: ignore
        path.write_text(yaml.safe_dump(data, sort_keys=False, default_flow_style=False),
                        encoding="utf-8")
    except ImportError:
        # Fallback: round-trip via json (loses comments — acceptable for state file)
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def _fallback_yaml(text: str) -> dict:
    """Tiny fallback parser — only handles the subset our spec uses.
    Strongly recommended: pip install pyyaml. This is a backup."""
    out: dict = {"spokes": []}
    cur: dict | None = None
    indent_stack: list[tuple[int, dict | list]] = [(0, out)]
    for raw in text.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        # Very minimal: detect "  - name:" entries and "    key: value" lines
        m = re.match(r"^(\s*)-\s+(\w+):\s*(.*)$", raw)
        if m:
            depth = len(m.group(1))
            cur = {m.group(2): m.group(3).strip().strip('"')}
            out.setdefault("spokes", []).append(cur)
            continue
        m = re.match(r"^(\s*)(\w+):\s*(.*)$", raw)
        if m and cur is not None:
            cur[m.group(2)] = m.group(3).strip().strip('"')
    return out


SPOKE_TEMPLATE = '''"""build_{name}.py — {title}

Auto-generated by Protocol Automaton spoke_smith.py at {ts}.
Spec: automaton/pending_spokes.yaml#{name}

{rationale}

Output: {name}.csv (workspace root)
Cache: .{name}_cache.json (TTL {ttl}h)
"""

import csv
import json
import time
import urllib.request
import urllib.error
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).parent
CACHE_FILE = ROOT / ".{name}_cache.json"
OUTPUT_FILE = ROOT / "{name}.csv"
CACHE_TTL_HOURS = {ttl}
SOURCE_URL = "{url}"
HEADERS = {{
    "User-Agent": "Mozilla/5.0 (Catalyst Edge Spoke / {name})",
    "Accept": "*/*",
}}


def load_cache():
    if not CACHE_FILE.exists():
        return None
    try:
        d = json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return None
    age_hours = (time.time() - d.get("ts", 0)) / 3600.0
    if age_hours > CACHE_TTL_HOURS:
        return None
    return d.get("payload")


def save_cache(payload):
    CACHE_FILE.write_text(json.dumps({{"ts": time.time(), "payload": payload}}),
                          encoding="utf-8")


def fetch():
    cached = load_cache()
    if cached is not None:
        print(f"  using cache (age < {{CACHE_TTL_HOURS}}h)")
        return cached
    try:
        req = urllib.request.Request(SOURCE_URL, headers=HEADERS)
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = resp.read().decode("utf-8", errors="replace")
        save_cache(body)
        return body
    except urllib.error.URLError as e:
        print(f"  FETCH FAILED: {{e}}")
        return None
    except Exception as e:  # noqa: BLE001
        print(f"  FETCH ERROR: {{type(e).__name__}}: {{e}}")
        return None


def parse(body):
    """TODO: implement parsing per spec output_schema.
    Expected output: list[dict] with keys ticker, ts, plus spoke-specific fields.
    Spec required fields: {fields_required}
    Spec output schema: {output_schema}
    """
    rows = []
    # ── PARSE LOGIC GOES HERE ─────────────────────────────────────────
    # The spoke_smith generator only stubs this; the spec author or a
    # follow-up agent fills in the parser. The skeleton lets the spoke
    # appear in the build_*.py glob immediately so the rest of the
    # pipeline (audit, weight onboarding) can probe it.
    # ──────────────────────────────────────────────────────────────────
    return rows


def write(rows):
    if not rows:
        # Write empty file with header so audit can detect "ran but no data"
        OUTPUT_FILE.write_text("ticker,ts,status\\n", encoding="utf-8")
        print(f"  wrote 0 rows to {{OUTPUT_FILE.name}} (empty)")
        return
    keys = list(rows[0].keys())
    with OUTPUT_FILE.open("w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=keys)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"  wrote {{len(rows)}} rows to {{OUTPUT_FILE.name}}")


def main():
    print(f"[{{datetime.now(timezone.utc).isoformat()}}] {name} fetching...")
    body = fetch()
    if body is None:
        print(f"  no body — exit 1")
        return 1
    rows = parse(body)
    write(rows)
    print(f"  status=ok rows={{len(rows)}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def generate_spoke_file(spec: dict) -> Path:
    name = spec["name"]
    out_path = ROOT / f"build_{name}.py"
    rationale = (spec.get("rationale") or "").strip()
    if "\n" in rationale:
        rationale = "\n".join(line.strip() for line in rationale.splitlines() if line.strip())
    code = SPOKE_TEMPLATE.format(
        name=name,
        title=spec.get("title", name),
        ts=dt.datetime.now(dt.timezone.utc).isoformat(),
        rationale=rationale[:400],
        ttl=int(spec.get("source", {}).get("ttl_hours", 24)),
        url=spec.get("source", {}).get("url", "ABOUT:BLANK"),
        fields_required=spec.get("fields_required", []),
        output_schema=spec.get("output_schema", {}),
    )
    out_path.write_text(code, encoding="utf-8")
    return out_path


def trial_run(name: str) -> tuple[bool, str]:
    script = ROOT / f"build_{name}.py"
    if not script.exists():
        return False, "script does not exist"
    try:
        result = subprocess.run(
            ["python3", str(script)],
            capture_output=True, text=True, timeout=60,
            cwd=str(ROOT),
        )
        return (result.returncode == 0,
                f"rc={result.returncode}  stdout={result.stdout[-200:]}")
    except subprocess.TimeoutExpired:
        return False, "trial run timeout (>60s)"
    except Exception as e:  # noqa: BLE001
        return False, f"{type(e).__name__}: {e}"


def find_next_eligible(spokes: list) -> dict | None:
    queued = [s for s in spokes if s.get("state") == "queued"]
    if not queued:
        return None
    queued.sort(key=lambda s: s.get("priority", 99))
    return queued[0]


def transition(state_data: dict, name: str, new_state: str) -> None:
    for s in state_data.get("spokes", []):
        if s.get("name") == name:
            s["state"] = new_state
            s["last_transition_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--next", action="store_true", help="ship highest-priority queued spoke")
    p.add_argument("--name", help="ship a specific spoke by name (overrides --next)")
    p.add_argument("--dry-run", action="store_true", help="don't write or transition")
    args = p.parse_args()

    if not QUEUE_PATH.exists():
        log(f"ERROR: queue file missing: {QUEUE_PATH}")
        return 2
    state_data = load_yaml(QUEUE_PATH)
    spokes = state_data.get("spokes", [])

    if args.name:
        target = next((s for s in spokes if s.get("name") == args.name), None)
        if not target:
            log(f"ERROR: --name {args.name} not in queue")
            return 2
    else:
        target = find_next_eligible(spokes)
        if not target:
            log("no eligible queued spokes")
            return 1

    name = target["name"]
    log(f"target spoke: {name}  priority={target.get('priority')}  state={target.get('state')}")

    if args.dry_run:
        log("DRY RUN — would generate build_{}.py".format(name))
        return 0

    out_path = generate_spoke_file(target)
    log(f"generated {out_path.name}  ({out_path.stat().st_size} bytes)")

    transition(state_data, name, "in_progress")
    state_data["last_run_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()
    dump_yaml(state_data, QUEUE_PATH)

    ok, msg = trial_run(name)
    log(f"trial run: ok={ok}  detail={msg}")

    if not ok:
        log("trial failed — leaving spoke in_progress for manual review")
        return 3

    log(f"DONE: {name} → in_progress (parser stub awaits human/agent fill-in)")
    log(f"NEXT: implement parse() in {out_path.name}, then run spoke_audit.py --name {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
